name: Release Linux Arm64
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release_arm64:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: alist-dev/desktop
          token: ${{ secrets.MY_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm" # Set this to npm, yarn or pnpm.

      - name: Install app dependencies and build web
        run: pnpm i

      - name: Replace version
        run: |
          npx tsx ./scripts/version.ts
          cat src-tauri/tauri.conf.json
        env:
          AD_VERSION: ${{ github.ref_name }}

      - name: Get AList version
        id: get-alist-version
        uses: fangqiuming/latest-release-version@v1.2.0-beta
        with:
          repository: AlistGo/alist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Rclone version
        id: get-rclone-version
        uses: fangqiuming/latest-release-version@v1.2.0-beta
        with:
          repository: rclone/rclone
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download sidecar
        run: npx tsx ./scripts/bin.ts
        env:
          TARGET_TRIPLE: aarch64-unknown-linux-gnu
          ALIST_VERSION: ${{ steps.get-alist-version.outputs.tag_name }} # v3.19.0
          RCLONE_VERSION: ${{ steps.get-rclone-version.outputs.tag_name }} # v1.63.0

      - uses: pguyot/arm-runner-action@v2.5.2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z
          cpu: cortex-a53
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # Install setup prerequisites
            apt-get update -y --allow-releaseinfo-change
            apt-get upgrade -y
            apt-get autoremove -y
            apt-get install curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash
            # Install framework specific packages
            apt-get install -y nodejs git
            # npm install next@latest react@latest react-dom@latest eslint-config-next@latest
            # Install build tools and tauri-cli requirements
            apt-get install -y libwebkit2gtk-4.0-dev build-essential wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
            # cargo install tauri-cli
            # Install frontend dependencies
            npm install
            # download sidecar
            export TARGET_TRIPLE=aarch64-unknown-linux-gnu
            export TAURI_PRIVATE_KEY=${{ secrets.TAURI_PRIVATE_KEY }}
            # npx tsx ./scripts/bin.ts
            sed -i 's/pnpm/npm run/g' src-tauri/tauri.conf.json
            # npm install -g pnpm
            # pnpm i
            # Build the application
            # cargo tauri build
            npm run tauri build

      - name: upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/deb/*.deb